version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=yalchat
      - POSTGRES_PASSWORD=yalchat
      - POSTGRES_DB=yalchat
    ports:
      - 5432:5432

volumes:
  postgres_data:
